#!/bin/sh
# Disable exit on non 0
set +e
mkdir -p build
mkdir -p dist

# DEBUG CONFIGURE
#(cd build && emconfigure cmake -DCMAKE_BUILD_TYPE=Debug ..) &&

# DOUBLE CONFIGURE
# Workaround for autogenerated `CMakeTmp/CheckSymbolExists.c`
# That contains logic that fails on first run
(cd build && emconfigure cmake .. || true) &&
(cd build && emconfigure cmake ..) &&
(cd build && emmake make VERBOSE=1 -j 16) &&
cp ./build/extern/openjpeg/bin/openjpegjs.js ./dist && 
cp ./build/extern/openjpeg/bin/openjpegjs.js.mem ./dist &&
cp ./build/extern/openjpeg/bin/openjpegwasm.js ./dist &&
cp ./build/extern/openjpeg/bin/openjpegwasm.wasm ./dist
