import { beforeAll, describe, expect, it } from "vitest"
import { existsSync, readFileSync } from "node:fs"
import { fileURLToPath } from "node:url"
import { dirname, resolve } from "node:path"

const __dirname = dirname(fileURLToPath(import.meta.url))
const distDir = resolve(__dirname, "../dist")
const fixturesDir = resolve(__dirname, "fixtures")

const ct1Encoded = readFileSync(resolve(fixturesDir, "j2k/CT1.j2k"))
const ct1Raw = readFileSync(resolve(fixturesDir, "raw/CT1.RAW"))
const ct2Encoded = readFileSync(resolve(fixturesDir, "j2k/CT2.j2k"))
const ct2Raw = readFileSync(resolve(fixturesDir, "raw/CT2.RAW"))
// CT-512x512-lossy.j2k is a real .91 (JPEG 2000 Lossy) payload extracted from
// a Cornerstone3D test DICOM. Uses an irreversible 9-7 wavelet, so byte
// equality with the original source pixels is not expected — but decoding is
// deterministic, so we pin the decoder's own output as a regression golden
// (CT-512x512-lossy.raw, generated by this codec and identical across the
// asm.js/wasm/decode-only variants).
const ctLossy = readFileSync(resolve(fixturesDir, "j2k/CT-512x512-lossy.j2k"))
const ctLossyRaw = readFileSync(resolve(fixturesDir, "raw/CT-512x512-lossy.raw"))

async function loadModule(modulePath) {
  const mod = await import(modulePath)
  const factory = mod.default ?? mod
  return await factory()
}

const buildVariants = [
  { name: "asm.js full (openjpegjs)", path: "../dist/openjpegjs.js", dist: "openjpegjs.js" },
  { name: "wasm full (openjpegwasm)", path: "../dist/openjpegwasm.js", dist: "openjpegwasm.js" },
  { name: "wasm decode-only", path: "../dist/openjpegwasm_decode.js", dist: "openjpegwasm_decode.js" },
]

describe.each(buildVariants)("openjpeg J2K decode — $name", ({ path, dist }) => {
  const isBuilt = existsSync(resolve(distDir, dist))
  let codec

  beforeAll(async () => {
    if (isBuilt) codec = await loadModule(path)
  })

  // In CI a missing dist means the build/artifact pipeline broke; fail loudly
  // instead of letting every skipIf() below silently skip the suite.
  it.runIf(process.env.CI)("dist is present in CI", () => {
    expect(isBuilt, `${dist} missing — build artifact was not replayed`).toBe(true)
  })

  it.skipIf(!isBuilt)(
    "decodes CT1.j2k to a 512x512 16-bit monochrome frame",
    () => {
      const decoder = new codec.J2KDecoder()
      decoder.getEncodedBuffer(ct1Encoded.length).set(ct1Encoded)
      decoder.decode()

      const frameInfo = decoder.getFrameInfo()
      expect(frameInfo.width).toBe(512)
      expect(frameInfo.height).toBe(512)
      expect(frameInfo.bitsPerSample).toBe(16)
      expect(frameInfo.componentCount).toBe(1)

      const decoded = decoder.getDecodedBuffer()
      expect(decoded.length).toBe(ct1Raw.length)
      expect(Buffer.from(decoded).equals(ct1Raw)).toBe(true)

      decoder.delete()
    }
  )

  it.skipIf(!isBuilt)("decodes CT2.j2k losslessly to CT2.RAW", () => {
    const decoder = new codec.J2KDecoder()
    decoder.getEncodedBuffer(ct2Encoded.length).set(ct2Encoded)
    decoder.decode()

    const decoded = decoder.getDecodedBuffer()
    expect(Buffer.from(decoded).equals(ct2Raw)).toBe(true)

    decoder.delete()
  })

  it.skipIf(!isBuilt)(
    "decodes a lossy 9-7 J2K (transfer syntax .91) matching the pinned golden output",
    () => {
      const decoder = new codec.J2KDecoder()
      decoder.getEncodedBuffer(ctLossy.length).set(ctLossy)
      decoder.decode()

      const frameInfo = decoder.getFrameInfo()
      expect(frameInfo.width).toBe(512)
      expect(frameInfo.height).toBe(512)
      expect(frameInfo.bitsPerSample).toBe(16)
      expect(frameInfo.componentCount).toBe(1)

      const decoded = decoder.getDecodedBuffer()
      expect(decoded.length).toBe(ctLossyRaw.length)
      expect(Buffer.from(decoded).equals(ctLossyRaw)).toBe(true)
      decoder.delete()
    }
  )
})

describe.each(buildVariants)("openjpeg J2K decode robustness — $name", ({ path, dist }) => {
  const isBuilt = existsSync(resolve(distDir, dist))
  let codec

  beforeAll(async () => {
    if (isBuilt) codec = await loadModule(path)
  })

  it.skipIf(!isBuilt)("throws when the encoded buffer is smaller than 4 bytes", () => {
    const decoder = new codec.J2KDecoder()
    const tooShort = new Uint8Array([0x00, 0x01, 0x02])
    decoder.getEncodedBuffer(tooShort.length).set(tooShort)

    expect(() => decoder.decode()).toThrow()

    decoder.delete()
  })

  it.skipIf(!isBuilt)("does not crash the process on a malformed/garbage buffer", () => {
    const decoder = new codec.J2KDecoder()
    const garbage = new Uint8Array(64)
    for (let i = 0; i < garbage.length; i++) garbage[i] = (i * 37 + 11) % 256
    decoder.getEncodedBuffer(garbage.length).set(garbage)

    // Malformed input must either throw or return without corrupting the
    // process (e.g. via an out-of-bounds heap write). Reaching this
    // expectation at all is the meaningful assertion here.
    expect(() => {
      try {
        decoder.decode()
      } catch (e) {
        // throwing is an acceptable, expected outcome for malformed input
      }
    }).not.toThrow()

    decoder.delete()
  })
})

const encoderVariants = buildVariants.filter((v) => !v.name.includes("decode-only"))

describe.each(encoderVariants)(
  "openjpeg J2K encode + round-trip — $name",
  ({ path, dist }) => {
    const isBuilt = existsSync(resolve(distDir, dist))
    let codec

    beforeAll(async () => {
      if (isBuilt) codec = await loadModule(path)
    })

    it.skipIf(!isBuilt)(
      "throws when encoder setup fails instead of returning a garbage buffer",
      () => {
        const frameInfo = {
          width: 512,
          height: 512,
          bitsPerSample: 16,
          componentCount: 1,
          isSigned: true,
        }
        const encoder = new codec.J2KEncoder()
        encoder.getDecodedBuffer(frameInfo).set(ct1Raw)
        // 40 decompositions -> numresolution 41, beyond OpenJPEG's maximum
        // (33), so opj_setup_encoder fails. encode() used to swallow this
        // and leave the full pre-sized allocation in the encoded buffer,
        // which callers then read back as a "successful" encode.
        encoder.setDecompositions(40)

        expect(() => encoder.encode()).toThrow()
        expect(encoder.getEncodedBuffer().length).toBe(0)

        encoder.delete()
      }
    )

    it.skipIf(!isBuilt)(
      "encodes CT1.RAW losslessly and decodes back to original bytes",
      () => {
        const frameInfo = {
          width: 512,
          height: 512,
          bitsPerSample: 16,
          componentCount: 1,
          isSigned: true,
        }
        const encoder = new codec.J2KEncoder()
        encoder.getDecodedBuffer(frameInfo).set(ct1Raw)
        encoder.encode()
        const encoded = encoder.getEncodedBuffer()
        expect(encoded.length).toBeGreaterThan(0)

        const decoder = new codec.J2KDecoder()
        decoder.getEncodedBuffer(encoded.length).set(encoded)
        decoder.decode()
        const decoded = decoder.getDecodedBuffer()

        expect(decoded.length).toBe(ct1Raw.length)
        expect(Buffer.from(decoded).equals(ct1Raw)).toBe(true)

        encoder.delete()
        decoder.delete()
      }
    )
  }
)
